// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Buttler.Test.Domain.Models
{
    public partial class Customers
    {
        public Customers()
        {
            OrderMasters = new HashSet<OrderMasters>();
            Tables = new HashSet<Tables>();
        }

        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Gender { get; set; }
        public string CustomerPhoneNumber { get; set; }

        public virtual ICollection<OrderMasters> OrderMasters { get; set; }
        public virtual ICollection<Tables> Tables { get; set; }
    }
}