// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Buttler.Test.Domain.Models
{
    public partial class OrderMasters
    {
        public OrderMasters()
        {
            OrderItems = new HashSet<OrderItems>();
        }

        public int Id { get; set; }
        public int? CustomerId { get; set; }
        public string StaffId { get; set; }
        public int? TableId { get; set; }
        public int? OrderStatus { get; set; }
        public decimal? Bill { get; set; }
        public DateTime? DateOfOrder { get; set; }

        public virtual Customers Customer { get; set; }
        public virtual AspNetUsers Staff { get; set; }
        public virtual Tables Table { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}